# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# Mor GiHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - girishtestapp1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:WebPublishMethod=Package /p:DeleteExistingFiles=True /p:SkipExtraFilesOnServer=True /p:_PackageTempDir="\testapp2"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: testapp2
          path: '/testapp2/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: testapp2
          path: testapp2

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with: 
          server: waws-prod-dm1-333.ftp.azurewebsites.windows.net
          username: aspnetapptest\$aspnetapptest
          password: ${{ FTP_PASSWD1 }}
          protocol: ftp
          local-dir: D:/testapp2/
          server-dir: /site/wwwroot/app1/          
